Vagrant.configure(2) do |config|

  config.vm.define :debian1 do |host|
    config.vm.box = "debian/stretch64"

    config.vm.hostname = "debian1"

    host.vm.network "private_network", ip: "10.10.12.101", virtualbox__intnet: "intranet"

    host.vm.provision "shell", path: "setup.sh"
    host.vm.provision "shell", path: "router.sh"
  end

  config.vm.define :debian2 do |host|
    config.vm.box = "debian/stretch64"

    config.vm.hostname = "debian2"

    host.vm.network "private_network", ip: "10.10.12.102", virtualbox__intnet: "intranet"

    host.vm.provision "shell", path: "setup.sh"
    host.vm.provision "shell", path: "advertisers.sh"
  end

  config.vm.define :debian3 do |host|
    config.vm.box = "debian/stretch64"

    config.vm.hostname = "debian3"

    host.vm.network "private_network", ip: "10.10.12.103", virtualbox__intnet: "intranet"
    
    host.vm.provision "shell", path: "setup.sh"
    host.vm.provision "shell", path: "advertisers.sh"
  end

end
